### ISSUE TITLE
Add a logo and badges to Readme

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_Smart-Device_Resources#13]
Change Readme to include logo and badges

Like this:

```
<h1 align="center">CyBear Jinni Smart Device Resources</h1>

<div align="center">

[![License: GPL v3](https://img.shields.io/badge/License-GPL%20v3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0) [<img src="https://badges.frapsoft.com/os/v1/open-source-200x33.png?v=103" height="20">](https://en.wikipedia.org/wiki/Open_source) 
</div>

[<div align="center"><img alt="CyBear Jinni Smart Device Resources image" height="400" src="https://user-images.githubusercontent.com/9304740/97477161-edf46c80-1957-11eb-8370-41e8d7879da9.png"></div>](https://github.com/CyBear-Jinni/CBJ_Smart-Home)

# Welcome!
```

<h1 align="center">CyBear Jinni Smart Device Resources</h1>

<div align="center">

[![License: GPL v3](https://img.shields.io/badge/License-GPL%20v3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0) [<img src="https://badges.frapsoft.com/os/v1/open-source-200x33.png?v=103" height="20">](https://en.wikipedia.org/wiki/Open_source) 
</div>

[<div align="center"><img alt="CyBear Jinni Smart Device Resources image" height="400" src="https://user-images.githubusercontent.com/9304740/97477161-edf46c80-1957-11eb-8370-41e8d7879da9.png"></div>](https://github.com/CyBear-Jinni/CBJ_Smart-Home)

# Welcome!

**Comment by Shweta200126** [comment]
Hey , Can I take this?

**Comment by guyluz11** [comment]
Sure @Shweta200126

**Comment by sourabhjain9887** [comment]
Have a look @guyluz11 , i added a logo and badges to Readme and generated a pull request.
78827a2

**Comment by Shweta200126** [comment]
I think @sourabhjain9887 did a very job at this. Thanks for assigning but its fine he did it already.I learnt somethings here too. Thanks @sourabhjain9887 .

**Comment by guyluz11** [comment]
If its ok by you @Shweta200126 than it is ok by me.
I  can fined new issue for you.
If you are interested please write me in the CyBear Jinni Discord server

[<img src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" height="80">](https://discord.gg/mUXfwUY)

**Comment by guyluz11** [comment]
Thanks @sourabhjain9887 and @Shweta200126 
I will now close this issue
