### ISSUE TITLE
Fix Readme text start position

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_Smart-Device_Resources#8]
The NanoPi Duo 2 readme have lines that are not aligned.

https://github.com/CyBear-Jinni/CBJ_Smart-Device_Resources/blob/master/devices_resources/nanopi_duo2/README.md

As you can see in the image the number 3 is forward to the command to execute "sudo ...".
And the first row is not in the same line as the last row.

<img src="https://user-images.githubusercontent.com/9304740/94748299-a7781600-0389-11eb-8963-aa580aef9411.png" height="300">

Please make all the rows start in the same line.
If it is more beautiful you can make the scripts to run that have row to themselves (starts with sudo and nano setup_..)  little bit forward.

**Comment by guyluz11** [comment]
@72y9op Leave a comment below for me to assign this issue to you

**Comment by ghost** [comment]
Hellow, i have resolved your problem, you can use an HTML tag on the README files, in this case, i use the <p> tag for solve your problem ! Check #10

**Comment by guyluz11** [comment]
@72y9op I have merged now the pull request.

Thanks
